# Site settings
title: Cognition Switch
# email: youremailaddress@gmail.com
# description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Carlos

# Social settings
# 500px_url:
# facebook_url:
# github_url:
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
# instagram_url: https://instagram.com
# linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
# pinterest_url:
# slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num"

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]

include: [_posts, _categories]